package com.appdirect.sdk.appmarket.api;

public enum EventType {
	SUBSCRIPTION_ORDER,
	SUBSCRIPTION_CHANGE,
	SUBSCRIPTION_CANCEL,
	SUBSCRIPTION_NOTICE,
	USER_ASSIGNMENT,
	USER_UNASSIGNMENT,
	USER_SYNC,
	USER_LINK,
	ACCOUNT_SYNC,
	ACCOUNT_UNSYNC,
	ADDON_ORDER,
	ADDON_BIND,
	ADDON_UNBIND,
	ADDON_CHANGE,
	ADDON_CANCEL
}
